dist: xenial

language: python

cache: pip

python: 3.6

services:
  - postgresql
  - docker

addons:
  postgresql: "10"

env:
  global:
  - DJANGO_SETTINGS_MODULE=nrc.conf.ci
  - DB_PASSWORD=
  - DB_USER=postgres
  - ALLOWED_HOSTS=openzaak.nl

install:
  - pip install -r requirements/ci.txt
  - pip install codecov
  - npm ci
  - npm run build

jobs:
  include:
    # Run jobs in parallel in stage Tests
    - stage: Tests
      name: "Unit tests"
      script:
        - python src/manage.py collectstatic --noinput --link
        - coverage run src/manage.py test src

    - name: "Code imports"
      before_install: skip
      install:
        - pip install -r requirements/ci.txt
      before_script: skip
      script: isort --recursive --check-only --diff .

    - name: "Code format"
      before_install: skip
      install:
        - pip install -r requirements/ci.txt
      before_script: skip
      script: black --check src

    - name: "Code style"
      before_install: skip
      install:
        - pip install flake8
      before_script: skip
      script: flake8 src

    - name: "Documentation build"
      install:
        - pip install pytest -r requirements/dev.txt
      before_script: skip
      script: cd docs && pytest check_sphinx.py -v --tb=auto

    - name: "Docker image"
      before_install: skip
      install: skip
      before_script: skip
      script: docker build .

    - stage: Publication
      name: "Docker image"
      before_install: skip
      install: skip
      before_script: skip
      script: echo "noop"
      after_success: echo "trigger deploy?"
      deploy:
        - provider: script
          script: bin/docker_push.sh latest
          on:
            branch: master

        - provider: script
          script: bin/docker_push.sh $TRAVIS_TAG
          on:
            tags: true

after_success:
  - codecov
