# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  mock:
    image: nginx:1.19
    volumes:
      - ./mocks.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/certs:ro
    ports:
      - 9000:80
      - 9001:443
